### ISSUE TITLE
LoggedStatement::bindColumn() does not work

### ISSUE THREAD

**Issue by pmjones** [atlasphp/Atlas.Pdo#15]
@dbraff see current 1.x branch, in tests/LoggedStatementTest::testBindColumn().

It appears that the double-indirection-by-reference does not work when binding a variable to a column result. Although I suppose it's not critical, it does represent a BC break. Any ideas on how to get that working?

If there can be no straightforward solution, I may have to break LoggedStatement into two classes: one for "transient" connections, that looks a lot like the v1.1.2 LoggedStatement, and one for "persistent" connections, that does not support bindColumn(). (See #16 for what that would look like.)

**Comment by dbraff** [comment]
Hi @pmjones, I checked out the current 1.x branch and wasn't able to find a straightforward solution to this either. That's unfortunate but the solution seems like a reasonable tradeoff to have to avoid that method when using both persistent connections and logged statements.

**Comment by pmjones** [comment]
Yeah, it's a tough one. Persistent connections under PDO have always been a hassle. :-/

So, to be clear, #16 is also a satisfactory solution for your situation? If so, I will merge it to 1.x and try for a release today.

**Comment by pmjones** [comment]
@dbraff Yeah, it's a tough one. Persistent connections under PDO have always been a hassle. :-/

So, to be clear, #16 is also a satisfactory solution for your situation? If so, I will merge it to 1.x and try for a release today.

**Comment by dbraff** [comment]
@pmjones, yeah to be honest I'm less than sure about the benefits of using persistent connections and probably wouldn't if I wasn't working with an already large existing codebase.

Yes, #16 is definitely a satisfactory solution. I've checked that branch and tested to ensure it works. Thank you again for all your work with this.

**Comment by pmjones** [comment]
@dbraff 

> probably wouldn't if I wasn't working with an already large existing codebase.

Story of my life. :-)

> Yes, #16 is definitely a satisfactory solution

SWEET.  Will roll a release this morning, barring the unforeseen.

And thank *you* for your patient assistance.

**Comment by dbraff** [comment]
@pmjones 

> Story of my life. :-)

Can definitely relate, and also should mention that MLAPHP has been big help with that :)

> SWEET. Will roll a release this morning, barring the unforeseen.
> 
> And thank _you_ for your patient assistance.

No problem! And looking forward!

**Comment by pmjones** [comment]
Fixed via #16.

**Comment by pmjones** [comment]
@dbraff the release, it is rolled https://github.com/atlasphp/Atlas.Pdo/releases/tag/1.2.0
