### ISSUE TITLE
The default for the optional type parameter on bindValue isn't null

### ISSUE THREAD

**Issue by far-blue** [atlasphp/Atlas.Pdo#6]
Hi all,

While trying out the query logging I found that the definition of the overridden bindValue method in LoggedStatement.php (here:         https://github.com/atlasphp/Atlas.Pdo/blob/50bd80965755179c5443be17e7bb8d86a85b9f9c/src/LoggedStatement.php#L48) needs to have `\PDO::PARAM_STR` rather than null for the optional $dataType parameter.

**Comment by froschdesign** [comment]
Reference: https://php.net/manual/pdostatement.bindvalue.php

**Comment by froschdesign** [comment]
Please see: #3

**Comment by pmjones** [comment]
Gah! Of course, thanks for this. #3 is now merged. Can you try the new "3.x" now and see if it works for you? Let me know if it does (or does not)!

**Comment by far-blue** [comment]
I'm not sure what you mean by the new "3.x" but as you merged to the "1.x" branch I pulled the latest of that branch and can confirm I no longer get an error :)

**Comment by pmjones** [comment]
Clearly I need more coffee. Yes, 1.x. Thanks!

**Comment by pmjones** [comment]
I just release 1.1.1 with this fix. Thanks everybody!

**Comment by far-blue** [comment]
great, thanks!

**Comment by far-blue** [comment]
Any chance packagist can be updated with the 1.1.1 release?

**Comment by pmjones** [comment]
Done. Apparently I need to go back and update all the Packagist hooks. Thanks for pointing it out, and sorry for the hassle.

**Comment by far-blue** [comment]
thanks :)
