### ISSUE TITLE
Logging bad request

### ISSUE THREAD

**Issue by ElGigi** [atlasphp/Atlas.Pdo#7]
Hi,

In case of bad SQL request, a PDO exception is throwed.
But logging appears after a good execution. Possible to do perform the logging in all cases with result (true/false) ?

Example of simple implementation to do that:
```php
    public function commit() : bool
    {
        $executionPerformed = false;
        $entry = $this->newLogEntry(__METHOD__);

        try {
            $result = $this->pdo->commit();
            $executionPerformed = true;
        } finally {
            $entry['performed'] = $executionPerformed;
            $this->addLogEntry($entry);
        }

        return $result;
    }
```

Regards.

**Comment by pmjones** [comment]
If you want to send this as a PR, I'll be happy to take it!

**Comment by ElGigi** [comment]
Looks at: https://github.com/atlasphp/Atlas.Pdo/pull/13

**Comment by pmjones** [comment]
Fixed by #13

**Comment by pmjones** [comment]
Thanks @ElGigi it's in 1.x now, look for a release today/tomorrow!

**Comment by pmjones** [comment]
@ElGigi the release, it is rolled https://github.com/atlasphp/Atlas.Pdo/releases/tag/1.2.0
