### ISSUE TITLE
Instance LoggedStatement create from native PDO::prepare cannot execute

### ISSUE THREAD

**Issue by consatan** [atlasphp/Atlas.Pdo#9]
```php
$connectionLocator = \Atlas\Pdo\ConnectionLocator::new(
    'mysql:dbname=db;host=127.0.0.1',
    'user',
    'pswd'
);
$connectionLocator->logQueries(true);

$pdo = $connectionLocator->getDefault()->getPdo();

// SQLBuilder is a 3th-party open source library
// 1st argument MUST BE a PDO instance
$sqlbuilder = new SQLBuilder($pdo);

// In the query method, will prepare the SQL and execute it
$result = $sqlbuilder->query('select * from user where id=?', $id)->fetchAll();

// The SQLBuilder query method look like this
function query(string $sql, ...$bind): PDOStatement
{
    $stm = $this->pdo->parepare($sql);
    foreach ($bind as $k => $v) {
        $stm->bindValue($k + 1, $v);
    }
    // LoggedStatement->execute() will throw an Error
    // Function name must be a string
    // at line 41
    return $stm->execute();
}
```

Because `ConectionLocator` enable the `logQueries`, the `PDO::ATTR_STATEMENT_CLASS` will set to the `LoggedStatement` class.

In `SQLBuilder` the `LoggedStatement` is create from native `PDO::prepare` method, so not call the `LoggedStatement::setLogEntry` and `LoggedStatement::setQueryLogger`. Then when run `LoggedStatement->execute()`, it will throw this error.

The `SQLBuilder` only required a `PDO` instance, I don't think this requirement is too much. So I think it's `Atlas PDO` issue.

**Comment by froschdesign** [comment]
@consatan 
> The SQLBuilder only required a PDO instance, I don't think this requirement is too much. So I think it's Atlas PDO issue.

Can you reproduce the issue also without the usage of a 3th-party library?

**Comment by consatan** [comment]
@froschdesign 

> Can you reproduce the issue also without the usage of a 3th-party library?

Sure

```php
$connectionLocator = \Atlas\Pdo\ConnectionLocator::new(
    'mysql:dbname=db;host=127.0.0.1',
    'user',
    'pswd'
);
$connectionLocator->logQueries(true);

$pdo = $connectionLocator->getDefault()->getPdo();

$stm = $pdo->prepare("select * from user where id=?");
$stm->execute([1]);  // Function name must be a string
```
